### ISSUE TITLE
[Epic] Collection Page

### ISSUE THREAD

**Issue by ipr0310** [signum-nft/signum-art#21]
Develop collection page with all its unique/common sections
(This page shows the collection details more deeply)

- [ ] Collection info section
- [ ] Social media links
- [ ] Marketplace components (Showing only items from the collection)
- [ ] Responsive layout (Audit in mobile, tablet, 1366x768, 1280x720 resolutions)
- [ ] Possible optimizations
