### ISSUE TITLE
[Epic] Landing Page

### ISSUE THREAD

**Issue by ipr0310** [signum-nft/signum-art#6]
Develop main landing page with all its sections

- [] Asset creation
- [] Main Section (Welcome section)
- [] Featured section
- [] Features section
- [] New items section
- [] Hot collections section
- [] Top creators section
- [] Responsive layout
