### ISSUE TITLE
[Epic] Profile Page

### ISSUE THREAD

**Issue by ipr0310** [signum-nft/signum-art#9]
Develop user profile page with all its unique/common sections.
(This page shows the artist details from his account, the collections and NFTs he/she created.)

- [ ] User info section
- [ ] Social media links
- [ ] Marketplace tab
- [ ] Created items tab
- [ ] Collections tab
- [ ] History tab
- [ ] Responsive layout (Audit in mobile, tablet, 1366x768, 1280x720 resolutions)
- [ ] Possible optimizations
